services:
  backend:
    build:
      context: . 
      dockerfile: backend/Dockerfile.backend
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: .                  
      dockerfile: frontend/Dockerfile.frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
